/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DocsBox: typeof import('./.vitepress/components/docs-box.vue')['default']
    EslintIgnoreList: typeof import('./.vitepress/components/eslint-ignore-list.vue')['default']
  }
}
