catalog:
  '@iconify/json': ^2.2.408
  '@nuxt/content': ^3.8.2
  '@types/node': ^24.3.3
  '@unocss/nuxt': ^66.5.6
  '@vinicunca/eslint-config': ^3.29.0
  '@vinicunca/perkakas': ^1.9.0
  '@vinicunca/unocss-preset': ^1.35.0
  better-sqlite3: ^12.4.1
  eslint: ^9.39.1
  eslint-plugin-format: ^1.0.2
  nuxt: ^4.2.1
  nuxt-og-image: ^5.1.12
  pohon-ui: ^1.0.16
  prettier: ^3.6.2
  type-fest: ^5.2.0
  typedoc: ^0.28.14
  unocss: ^66.5.6
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
